accessControl:
  salt: 6OvB96kgImJy64zqAgbMJSTWcPUcot2D
  userfile: /octoprint/octoprint/users.yaml
api:
  allowCrossOrigin: true
  key: F3F71094F39E43DEABFB9AE607DC834F
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1645700400
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1646055600
      _plugins:
        read_until: 1647406800
      _releases:
        read_until: 1647426600
  discovery:
    upnpUuid: 5296d074-07d8-4ee3-9095-1767bd8b538a
  errortracking:
    unique_id: 865eedd6-f256-4f5e-8daf-3aa07dcc31e1
  gcodeviewer:
    _config_version: 1
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: 6b276e6f-df19-4042-887a-e9f3709e0d53
  uicustomizer:
    disableTermInactive: true
    mainTabs:
    - - control_link
      - false
      - false
      - fas fa-expand-arrows-alt
      - true
      - false
    - - temp_link
      - false
      - false
      - fas fa-thermometer-half
      - true
      - false
    - - timelapse_link
      - true
      - false
      - fas fa-film
      - true
      - false
    - - term_link
      - true
      - false
      - fas fa-terminal
      - true
      - false
    - - gcode_link
      - true
      - false
      - fab fa-codepen
      - true
      - false
    - - tab_plugin_prettygcode_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    rows:
    - _00#sidebar_plugin_action_command_notification_wrapper: true
      _01#connection_wrapper: true
      _02#UICGcodeVWidget: true
      _03#UICWebCamWidget: false
    - _00#files_wrapper: true
      _01div.UICmainTabs: true
    - _00#sidebar_plugin_firmware_check_warning_wrapper: true
      _01#UICTempWidget: true
      _02#state_wrapper: true
      _03#sidebar_plugin_firmware_check_info_wrapper: true
    themeVersion: 0.2.9.5
    topIconSort:
    - navbar_plugin_prettygcode
    - navbar_plugin_action_command_prompt
    - navbar_plugin_logging_seriallog
    - navbar_plugin_logging_plugintimingslog
    widths:
    - '3'
    - '6'
    - '3'
  virtual_printer:
    _config_version: 1
printerProfiles:
  default: _default
serial:
  autoconnect: true
server:
  allowFraming: true
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: BolExszqtliKcOXiyGqdDyvedCKU0pV3
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
